version: '3'

networks:
  api-network:
    driver: bridge

services:
  api:
    entrypoint: ['/bin/bash', './entrypoint.sh']
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - 'api-network'
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - 'api-network'
