version: '3'

networks:
  api-network:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - 'api-network'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    networks:
      - 'api-network'

    volumes:
      - .:/api
      - node_modules:/api/node_modules
      - postgres-data:/var/lib/postgresql/data

volumes:
  node_modules: {}
  postgres-data: {}
